env:
  browser: true
  es2021: true
  node: true
  jasmine: true
extends: ['eslint:recommended', 'plugin:react/recommended']
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  react/prop-types: off
}
parser: babel-eslint
