export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const LOAD_PICTURES = "LOAD_PICTURES";
export const REMOVE_PICTURES = "REMOVE_PICTURES";
export const SEARCH_PICTURES = "SEARCH_PICTURES";